spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instagramDB
    username: postgres
    password: 1317
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true